-- migrations/0059_fk_on_delete_restrict.sql
-- GH #297: Change purchaseOrders.vendorId and salesOrders.customerId FK
-- actions from ON DELETE SET NULL → ON DELETE RESTRICT.
--
-- Rationale:
-- Setting vendor_id or customer_id to NULL when the parent entity is deleted
-- silently orphans financial records. A purchase order without a vendor or a
-- sales order without a customer cannot be meaningfully reconciled, invoiced,
-- or audited. RESTRICT forces callers to explicitly handle the association
-- before deletion (archive the entity, reassign the order, etc.).
--
-- Implementation:
-- PostgreSQL requires DROP + re-add to change the ON DELETE action.
-- The DROP is idempotent (IF EXISTS). The ADD uses IF NOT EXISTS via a
-- DO $$ guard so the migration is safe to re-run.
--
-- Constraint names (auto-generated by PostgreSQL when created without an
-- explicit CONSTRAINT clause):
--   purchase_orders.vendor_id  → purchase_orders_vendor_id_fkey  (migration 0004)
--   sales_orders.customer_id   → sales_orders_customer_id_fkey   (migration 0001)

-- purchase_orders.vendor_id: SET NULL → RESTRICT
ALTER TABLE purchase_orders
  DROP CONSTRAINT IF EXISTS purchase_orders_vendor_id_fkey;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'purchase_orders_vendor_id_fkey'
      AND conrelid = 'purchase_orders'::regclass
  ) THEN
    ALTER TABLE purchase_orders
      ADD CONSTRAINT purchase_orders_vendor_id_fkey
      FOREIGN KEY (vendor_id) REFERENCES vendors(id) ON DELETE RESTRICT;
  END IF;
END $$;

-- sales_orders.customer_id: SET NULL → RESTRICT
ALTER TABLE sales_orders
  DROP CONSTRAINT IF EXISTS sales_orders_customer_id_fkey;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'sales_orders_customer_id_fkey'
      AND conrelid = 'sales_orders'::regclass
  ) THEN
    ALTER TABLE sales_orders
      ADD CONSTRAINT sales_orders_customer_id_fkey
      FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE RESTRICT;
  END IF;
END $$;
