import type { Role } from './types';

export const commandNames = [
  'createBatch',
  'updateBatch',
  'deleteBatch',
  'postPurchaseReceipt',
  'createPurchaseOrder',
  'updatePurchaseOrder',
  'addPurchaseOrderLine',
  'updatePurchaseOrderLine',
  'removePurchaseOrderLine',
  'approvePurchaseOrder',
  'receivePurchaseOrder',
  'cancelPurchaseOrder',
  'adjustBatchQuantity',
  'setBatchPrice',
  'setBatchLotInfo',
  'attachBatchPhoto',
  'importBatchesCsv',
  'createSalesOrder',
  'addSalesOrderLine',
  'updateSalesOrderLine',
  'removeSalesOrderLine',
  'reserveInventoryForOrder',
  'priceSalesOrder',
  'confirmSalesOrder',
  'cancelSalesOrder',
  'postSalesOrder',
  'allocateOrderToFulfillment',
  'applyClientCredit',
  'setDeliveryWindow',
  'logPayment',
  'allocatePayment',
  'unallocatePayment',
  'refundPayment',
  'applyEarlyPayDiscount',
  'createVendorBill',
  'approveVendorBill',
  'scheduleVendorPayment',
  'recordVendorPayment',
  'voidVendorPayment',
  'createPickList',
  'recordWeighAndPack',
  'markOrderFulfilled',
  'printLabels',
  'adjustFulfillmentLine',
  'approveConnectorRequest',
  'rejectConnectorRequest',
  'routeConnectorRequest',
  'createCorrectionJournalEntry',
  'reverseCommandById',
  'restoreFromBackupPoint',
  'repriceOrder',
  'postPeriodAdjustments',
  'lockPeriod',
  'archivePeriod'
] as const;

export type CommandName = (typeof commandNames)[number];

export const commandLabels: Record<CommandName, string> = {
  createBatch: 'Create batch',
  updateBatch: 'Update batch',
  deleteBatch: 'Delete batch',
  postPurchaseReceipt: 'Process intake',
  createPurchaseOrder: 'Create purchase order',
  updatePurchaseOrder: 'Update purchase order',
  addPurchaseOrderLine: 'Add purchase order line',
  updatePurchaseOrderLine: 'Update purchase order line',
  removePurchaseOrderLine: 'Remove purchase order line',
  approvePurchaseOrder: 'Approve purchase order',
  receivePurchaseOrder: 'Receive purchase order to intake',
  cancelPurchaseOrder: 'Cancel purchase order',
  adjustBatchQuantity: 'Adjust batch quantity',
  setBatchPrice: 'Set batch price',
  setBatchLotInfo: 'Set lot info',
  attachBatchPhoto: 'Attach batch photo',
  importBatchesCsv: 'Import batches CSV',
  createSalesOrder: 'Create sales order',
  addSalesOrderLine: 'Add sales order line',
  updateSalesOrderLine: 'Update sales order line',
  removeSalesOrderLine: 'Remove sales order line',
  reserveInventoryForOrder: 'Reserve inventory',
  priceSalesOrder: 'Price sales order',
  confirmSalesOrder: 'Confirm sales order',
  cancelSalesOrder: 'Cancel sales order',
  postSalesOrder: 'Post sales order',
  allocateOrderToFulfillment: 'Allocate to fulfillment',
  applyClientCredit: 'Apply client credit',
  setDeliveryWindow: 'Set delivery window',
  logPayment: 'Log payment',
  allocatePayment: 'Allocate payment',
  unallocatePayment: 'Unallocate payment',
  refundPayment: 'Refund payment',
  applyEarlyPayDiscount: 'Apply early-pay discount',
  createVendorBill: 'Create vendor bill',
  approveVendorBill: 'Approve vendor bill',
  scheduleVendorPayment: 'Schedule vendor payment',
  recordVendorPayment: 'Record vendor payment',
  voidVendorPayment: 'Void vendor payment',
  createPickList: 'Create pick list',
  recordWeighAndPack: 'Record weigh and pack',
  markOrderFulfilled: 'Mark order fulfilled',
  printLabels: 'Print labels',
  adjustFulfillmentLine: 'Adjust fulfillment line',
  approveConnectorRequest: 'Approve connector request',
  rejectConnectorRequest: 'Reject connector request',
  routeConnectorRequest: 'Route connector request',
  createCorrectionJournalEntry: 'Create correction journal entry',
  reverseCommandById: 'Reverse command',
  restoreFromBackupPoint: 'Preview backup restore',
  repriceOrder: 'Reprice order',
  postPeriodAdjustments: 'Post period adjustments',
  lockPeriod: 'Lock period',
  archivePeriod: 'Archive period'
};

export const commandMinRole: Record<CommandName, Role> = {
  createBatch: 'operator',
  updateBatch: 'operator',
  deleteBatch: 'manager',
  postPurchaseReceipt: 'operator',
  createPurchaseOrder: 'operator',
  updatePurchaseOrder: 'operator',
  addPurchaseOrderLine: 'operator',
  updatePurchaseOrderLine: 'operator',
  removePurchaseOrderLine: 'operator',
  approvePurchaseOrder: 'manager',
  receivePurchaseOrder: 'operator',
  cancelPurchaseOrder: 'manager',
  adjustBatchQuantity: 'manager',
  setBatchPrice: 'operator',
  setBatchLotInfo: 'operator',
  attachBatchPhoto: 'operator',
  importBatchesCsv: 'operator',
  createSalesOrder: 'operator',
  addSalesOrderLine: 'operator',
  updateSalesOrderLine: 'operator',
  removeSalesOrderLine: 'operator',
  reserveInventoryForOrder: 'operator',
  priceSalesOrder: 'operator',
  confirmSalesOrder: 'operator',
  cancelSalesOrder: 'manager',
  postSalesOrder: 'operator',
  allocateOrderToFulfillment: 'operator',
  applyClientCredit: 'manager',
  setDeliveryWindow: 'operator',
  logPayment: 'operator',
  allocatePayment: 'operator',
  unallocatePayment: 'manager',
  refundPayment: 'manager',
  applyEarlyPayDiscount: 'manager',
  createVendorBill: 'operator',
  approveVendorBill: 'manager',
  scheduleVendorPayment: 'manager',
  recordVendorPayment: 'manager',
  voidVendorPayment: 'manager',
  createPickList: 'operator',
  recordWeighAndPack: 'operator',
  markOrderFulfilled: 'operator',
  printLabels: 'operator',
  adjustFulfillmentLine: 'operator',
  approveConnectorRequest: 'operator',
  rejectConnectorRequest: 'operator',
  routeConnectorRequest: 'operator',
  createCorrectionJournalEntry: 'manager',
  reverseCommandById: 'manager',
  restoreFromBackupPoint: 'owner',
  repriceOrder: 'manager',
  postPeriodAdjustments: 'owner',
  lockPeriod: 'owner',
  archivePeriod: 'owner'
};

export const reversibleCommands = new Set<CommandName>([
  'postPurchaseReceipt',
  'approvePurchaseOrder',
  'receivePurchaseOrder',
  'postSalesOrder',
  'logPayment',
  'allocatePayment',
  'createVendorBill',
  'recordVendorPayment',
  'markOrderFulfilled',
  'approveConnectorRequest',
  'routeConnectorRequest',
  'postPeriodAdjustments'
]);
