import type { Role } from './types';

export const commandNames = [
  'createBatch',
  'updateBatch',
  'deleteBatch',
  'postPurchaseReceipt',
  'createPurchaseOrder',
  'updatePurchaseOrder',
  'addPurchaseOrderLine',
  'updatePurchaseOrderLine',
  'removePurchaseOrderLine',
  'finalizePurchaseOrder',
  'unfinalizePurchaseOrder',
  'approvePurchaseOrder',
  'receivePurchaseOrder',
  'cancelPurchaseOrder',
  'recordVendorPrepayment',
  'rejectBatch',
  'flagBatch',
  'verifyAllIntake',
  'adjustBatchQuantity',
  'setInventoryStatus',
  'transferInventoryLocation',
  'transferInventoryOwnership',
  'setBatchPrice',
  'setBatchLotInfo',
  'attachBatchPhoto',
  'uploadBatchMedia',
  'setBatchMediaRole',
  'publishBatchMedia',
  'deleteBatchMedia',
  'importBatchesCsv',
  'applyTags',
  'createSalesOrder',
  'addSalesOrderLine',
  'updateSalesOrderLine',
  'removeSalesOrderLine',
  'reserveInventoryForOrder',
  'priceSalesOrder',
  'confirmSalesOrder',
  'cancelSalesOrder',
  'postSalesOrder',
  'allocateOrderToFulfillment',
  'applyClientCredit',
  'setDeliveryWindow',
  'logPayment',
  'allocatePayment',
  'unallocatePayment',
  'refundPayment',
  'applyDiscount',
  'postTransactionLedgerRow',
  'upsertTransactionType',
  'createVendorBill',
  'approveVendorBill',
  'scheduleVendorPayment',
  'recordVendorPayment',
  'voidVendorPayment',
  'createPickList',
  'recordWeighAndPack',
  'markOrderFulfilled',
  'printLabels',
  'adjustFulfillmentLine',
  'approveConnectorRequest',
  'rejectConnectorRequest',
  'routeConnectorRequest',
  'createCorrectionJournalEntry',
  'reverseCommandById',
  'documentCommandFailure',
  'restoreFromBackupPoint',
  'repriceOrder',
  'postPeriodAdjustments',
  'lockPeriod',
  'archivePeriod',
  'createVendor',
  'createCustomerNeed',
  'updateCustomerNeed',
  'createVendorSupply',
  'updateVendorSupply',
  'acceptMatchmakingMatch',
  'dismissMatchmakingMatch',
  'reopenMatchmakingMatch',
  'updateMatchmakingSettings',
  'noteMatchmakingOutreach',
  'dismissMatchmakingWorkQueueItem',
  'setItemAlias',
  'createReferee',
  'updateReferee',
  'addRefereeRelationship',
  'updateRefereeRelationship',
  'deactivateRefereeRelationship',
  'voidRefereeCredit',
  'createPaymentProcessor',
  'markUserFeeCollected',
  'updateProcessorFeeStatus',
  'setCustomerCreditLimit',
  'revertCustomerCreditToEngine',
  'snoozeCustomerCreditReminder',
  'setCustomerEngineMax',
  'setCustomerStance',
  'disableCreditEngineForCustomer',
  'enableCreditEngineForCustomer',
  'createCreditEngineStance',
  'updateCreditEngineStance',
  'deleteCreditEngineStance',
  'setCreditEngineConfig',
  'bulkRevertCustomersToEngine',
  'setLineLandedCost',
  'setCustomerPricingRule',
  'setDefaultPricingRule',
  'updateSystemSetting',
  'mintPhotoUploadToken',
  'revokePhotoUploadToken',
  'createCustomerSheetSnapshot',
  'setLineBelowFloorReason',
  'resolveVendorApproval',
  'releaseLineForPicking',
  'releaseLinesForPicking',
  'recallLineFromPicking',
  'acknowledgeWarehouseAlert',
  'returnPickedUnits',
  'cancelFulfillmentLine',
  // CAP-033 / TER-1564 — entity profiles / contacts system
  'createContact',
  'updateContact',
  'archiveContact',
  'addContactRole',
  'linkContactToExistingEntity',
  'linkContactToUser',
  'createAppointment',
  'updateAppointment',
  'cancelAppointment',
  'completeAppointment',
  'updateVendor',
  'updateProcessor',
  'createItem',
  'updateItem',
  'toggleItemStatus',
  'resolveInvoiceDispute',
  'rejectInvoiceDispute',
  // D2 — merge candidate review (RBAC + audit trail)
  'approveMergeCandidate',
  'dismissMergeCandidate'
] as const;

// Commands whose frontend surface is deferred to a follow-up. The parity
// audit allows these to exist in commandNames without a runCommand call in
// src/client/. Each entry MUST link to a tracking issue.
//
// - setCustomerEngineMax / setCustomerStance / disableCreditEngineForCustomer
//   / createCreditEngineStance / updateCreditEngineStance / deleteCreditEngineStance
//   / bulkRevertCustomersToEngine: filed at #111 (Credit Engine admin surfaces
//   missing from PR #50's Settings → Credit Engine panel — only the global
//   config form landed; per-stance + per-customer admin actions deferred).
export const internalOnlyCommandNames = [
  'routeConnectorRequest',
  'setCustomerEngineMax',
  'setCustomerStance',
  'disableCreditEngineForCustomer',
  'createCreditEngineStance',
  'updateCreditEngineStance',
  'deleteCreditEngineStance',
  'bulkRevertCustomersToEngine',
  // TER-1658: CSV import retired from MVP intake; backend rejects with guidance.
  'importBatchesCsv',
  // TER-1660: Label printing deferred to backlog; backend remains for future use.
  'printLabels',
  // TER-1664: Connectors and processors removed from MVP nav.
  'approveConnectorRequest',
  'rejectConnectorRequest',
  'createPaymentProcessor',
  'updateProcessor',
  'markUserFeeCollected',
  'updateProcessorFeeStatus',
] as const;

// Commands that have been wired to the backend but whose frontend runCommand surface
// is pending. Remove from this list when the frontend PR lands so that parity
// enforcement kicks back in.
//
// CAP-030 wired (SalesView, OperationsViews, PickLineScreen) — removed 2026-06-04:
//   releaseLineForPicking, releaseLinesForPicking, recallLineFromPicking,
//   acknowledgeWarehouseAlert, returnPickedUnits, cancelFulfillmentLine
//
// TER-1564 / CAP-033 partially wired:
//   Wired (removed): createContact (ContactCreateModal), createAppointment/
//   updateAppointment (AppointmentModal), cancelAppointment/completeAppointment
//   (ContactAppointmentsPanel)
export const pendingFrontendCommandNames = [
  // TER-1564 / CAP-033 — contacts/entity profiles not yet surfaced
  'updateContact',
  'archiveContact',
  'addContactRole',
  'linkContactToExistingEntity',
  'linkContactToUser',
  'updateVendor',
  'updateProcessor',
] as const;


export type CommandName = (typeof commandNames)[number];

export type ReversalDisposition = 'reversible' | 'offsettable' | 'terminal';

export interface ReversalPolicy {
  disposition: ReversalDisposition;
  guidance: string;
}

export const commandLabels: Record<CommandName, string> = {
  createBatch: 'Create batch (requires PO line)',
  updateBatch: 'Update batch',
  deleteBatch: 'Delete batch',
  postPurchaseReceipt: 'Process intake',
  createPurchaseOrder: 'Create purchase order',
  updatePurchaseOrder: 'Update purchase order',
  addPurchaseOrderLine: 'Add purchase order line',
  updatePurchaseOrderLine: 'Update purchase order line',
  removePurchaseOrderLine: 'Remove purchase order line',
  finalizePurchaseOrder: 'Finalize purchase order',
  unfinalizePurchaseOrder: 'Unfinalize purchase order',
  approvePurchaseOrder: 'Approve purchase order',
  receivePurchaseOrder: 'Receive purchase order to intake',
  cancelPurchaseOrder: 'Cancel purchase order',
  recordVendorPrepayment: 'Record vendor prepayment',
  rejectBatch: 'Reject intake lot',
  flagBatch: 'Flag intake lot for attention',
  verifyAllIntake: 'Verify all intake as expected',
  adjustBatchQuantity: 'Adjust batch quantity',
  setInventoryStatus: 'Set inventory status',
  transferInventoryLocation: 'Transfer inventory location',
  transferInventoryOwnership: 'Transfer inventory ownership',
  setBatchPrice: 'Set batch price',
  setBatchLotInfo: 'Set lot info',
  attachBatchPhoto: 'Attach batch photo',
  uploadBatchMedia: 'Upload batch media',
  setBatchMediaRole: 'Set batch media role',
  publishBatchMedia: 'Publish batch media',
  deleteBatchMedia: 'Delete batch media',
  importBatchesCsv: 'Import batches CSV',
  applyTags: 'Apply tags',
  createSalesOrder: 'Create sales order',
  addSalesOrderLine: 'Add sales order line',
  updateSalesOrderLine: 'Update sales order line',
  removeSalesOrderLine: 'Remove sales order line',
  reserveInventoryForOrder: 'Reserve inventory',
  priceSalesOrder: 'Price sales order',
  confirmSalesOrder: 'Confirm sales order',
  cancelSalesOrder: 'Cancel sales order',
  postSalesOrder: 'Post sales order',
  allocateOrderToFulfillment: 'Allocate to fulfillment',
  applyClientCredit: 'Apply client credit',
  setDeliveryWindow: 'Set delivery window',
  logPayment: 'Log payment',
  allocatePayment: 'Allocate payment',
  unallocatePayment: 'Unallocate payment',
  refundPayment: 'Refund payment',
  applyDiscount: 'Apply discount',
  postTransactionLedgerRow: 'Post transaction ledger row',
  upsertTransactionType: 'Save transaction type',
  createVendorBill: 'Create vendor bill',
  approveVendorBill: 'Approve vendor bill',
  scheduleVendorPayment: 'Schedule vendor payment',
  recordVendorPayment: 'Record vendor payment',
  voidVendorPayment: 'Void vendor payment',
  createPickList: 'Create pick list',
  recordWeighAndPack: 'Record weigh and pack',
  markOrderFulfilled: 'Mark order fulfilled',
  printLabels: 'Print labels',
  adjustFulfillmentLine: 'Adjust fulfillment line',
  approveConnectorRequest: 'Approve connector request',
  rejectConnectorRequest: 'Reject connector request',
  routeConnectorRequest: 'Reassign inbound request',
  createCorrectionJournalEntry: 'Create correction journal entry',
  reverseCommandById: 'Reverse command',
  documentCommandFailure: 'Document command failure',
  restoreFromBackupPoint: 'Preview backup restore',
  repriceOrder: 'Reprice order',
  postPeriodAdjustments: 'Post period adjustments',
  lockPeriod: 'Lock period',
  archivePeriod: 'Archive period',
  createVendor: 'Create vendor',
  createCustomerNeed: 'Create customer need',
  updateCustomerNeed: 'Update customer need',
  createVendorSupply: 'Create vendor stock',
  updateVendorSupply: 'Update vendor stock',
  acceptMatchmakingMatch: 'Accept match',
  dismissMatchmakingMatch: 'Dismiss match',
  reopenMatchmakingMatch: 'Reopen matchmaking match',
  updateMatchmakingSettings: 'Update matchmaking settings',
  noteMatchmakingOutreach: 'Note matchmaking outreach',
  dismissMatchmakingWorkQueueItem: 'Dismiss matchmaking work queue item',
  setItemAlias: 'Set strain alias',
  createReferee: 'Create referee',
  updateReferee: 'Update referee',
  addRefereeRelationship: 'Add referee relationship',
  updateRefereeRelationship: 'Update referee relationship',
  deactivateRefereeRelationship: 'Deactivate referee relationship',
  voidRefereeCredit: 'Void referee credit',
  createPaymentProcessor: 'Create payment processor',
  markUserFeeCollected: 'Mark user fee collected',
  updateProcessorFeeStatus: 'Update processor fee status',
  setCustomerCreditLimit: 'Set customer credit limit',
  revertCustomerCreditToEngine: 'Revert customer credit to engine',
  snoozeCustomerCreditReminder: 'Snooze credit review reminder',
  setCustomerEngineMax: 'Set customer engine max',
  setCustomerStance: 'Set customer credit stance',
  disableCreditEngineForCustomer: 'Disable credit engine for customer',
  enableCreditEngineForCustomer: 'Enable credit engine for customer',
  createCreditEngineStance: 'Create credit engine stance',
  updateCreditEngineStance: 'Update credit engine stance',
  deleteCreditEngineStance: 'Delete credit engine stance',
  setCreditEngineConfig: 'Update credit engine config',
  bulkRevertCustomersToEngine: 'Bulk revert customers to engine',
  setLineLandedCost: 'Set landed COGS',
  setCustomerPricingRule: 'Set customer pricing rule',
  setDefaultPricingRule: 'Set default pricing rule',
  updateSystemSetting: 'Update system setting',
  mintPhotoUploadToken: 'Mint photo upload share link',
  revokePhotoUploadToken: 'Revoke photo upload share link',
  createCustomerSheetSnapshot: 'Persist customer sheet snapshot',
  setLineBelowFloorReason: 'Set below-floor reason on sale line',
  resolveVendorApproval: 'Resolve vendor approval on sale line',
  releaseLineForPicking: 'Release line for picking',
  releaseLinesForPicking: 'Release lines for picking (bulk)',
  recallLineFromPicking: 'Recall line from picking',
  acknowledgeWarehouseAlert: 'Acknowledge warehouse alert',
  returnPickedUnits: 'Return picked units',
  cancelFulfillmentLine: 'Cancel fulfillment line',
  // CAP-033 / TER-1564
  createContact: 'Create contact',
  updateContact: 'Update contact',
  archiveContact: 'Archive contact',
  addContactRole: 'Add role to contact',
  linkContactToExistingEntity: 'Link contact to existing entity',
  linkContactToUser: 'Link contact to user account',
  createAppointment: 'Create appointment',
  updateAppointment: 'Update appointment',
  cancelAppointment: 'Cancel appointment',
  completeAppointment: 'Complete appointment',
  updateVendor: 'Update vendor',
  updateProcessor: 'Update processor',
  createItem: 'Create item',
  updateItem: 'Update item',
  toggleItemStatus: 'Toggle item status',
  resolveInvoiceDispute: 'Resolve invoice dispute',
  rejectInvoiceDispute: 'Reject invoice dispute',
  // D2 — merge candidate review
  approveMergeCandidate: 'Mark merge candidate reviewed',
  dismissMergeCandidate: 'Dismiss merge candidate'
};

export const commandMinRole: Record<CommandName, Role> = {
  createBatch: 'operator',
  updateBatch: 'operator',
  deleteBatch: 'manager',
  postPurchaseReceipt: 'operator',
  createPurchaseOrder: 'operator',
  updatePurchaseOrder: 'operator',
  addPurchaseOrderLine: 'operator',
  updatePurchaseOrderLine: 'operator',
  removePurchaseOrderLine: 'operator',
  finalizePurchaseOrder: 'operator',
  unfinalizePurchaseOrder: 'operator',
  approvePurchaseOrder: 'manager',
  receivePurchaseOrder: 'operator',
  cancelPurchaseOrder: 'manager',
  recordVendorPrepayment: 'manager',
  rejectBatch: 'operator',
  flagBatch: 'operator',
  verifyAllIntake: 'operator',
  adjustBatchQuantity: 'manager',
  setInventoryStatus: 'manager',
  transferInventoryLocation: 'operator',
  transferInventoryOwnership: 'manager',
  setBatchPrice: 'operator',
  setBatchLotInfo: 'operator',
  attachBatchPhoto: 'operator',
  uploadBatchMedia: 'operator',
  setBatchMediaRole: 'operator',
  publishBatchMedia: 'operator',
  deleteBatchMedia: 'operator',
  importBatchesCsv: 'operator',
  applyTags: 'operator',
  createSalesOrder: 'operator',
  addSalesOrderLine: 'operator',
  updateSalesOrderLine: 'operator',
  removeSalesOrderLine: 'operator',
  reserveInventoryForOrder: 'operator',
  priceSalesOrder: 'operator',
  confirmSalesOrder: 'operator',
  cancelSalesOrder: 'manager',
  postSalesOrder: 'operator',
  allocateOrderToFulfillment: 'operator',
  applyClientCredit: 'manager',
  setDeliveryWindow: 'operator',
  logPayment: 'operator',
  allocatePayment: 'operator',
  unallocatePayment: 'manager',
  refundPayment: 'manager',
  applyDiscount: 'manager',
  postTransactionLedgerRow: 'manager',
  upsertTransactionType: 'manager',
  createVendorBill: 'operator',
  approveVendorBill: 'manager',
  scheduleVendorPayment: 'manager',
  recordVendorPayment: 'manager',
  voidVendorPayment: 'manager',
  createPickList: 'operator',
  recordWeighAndPack: 'operator',
  markOrderFulfilled: 'operator',
  printLabels: 'operator',
  adjustFulfillmentLine: 'operator',
  approveConnectorRequest: 'operator',
  rejectConnectorRequest: 'operator',
  routeConnectorRequest: 'operator',
  createCorrectionJournalEntry: 'manager',
  reverseCommandById: 'manager',
  documentCommandFailure: 'manager',
  restoreFromBackupPoint: 'owner',
  repriceOrder: 'manager',
  postPeriodAdjustments: 'owner',
  lockPeriod: 'owner',
  archivePeriod: 'owner',
  createVendor: 'operator',
  createCustomerNeed: 'operator',
  updateCustomerNeed: 'operator',
  createVendorSupply: 'operator',
  updateVendorSupply: 'operator',
  acceptMatchmakingMatch: 'operator',
  dismissMatchmakingMatch: 'operator',
  reopenMatchmakingMatch: 'manager',
  updateMatchmakingSettings: 'manager',
  noteMatchmakingOutreach: 'operator',
  dismissMatchmakingWorkQueueItem: 'operator',
  setItemAlias: 'manager',
  createReferee: 'manager',
  updateReferee: 'manager',
  addRefereeRelationship: 'manager',
  updateRefereeRelationship: 'manager',
  deactivateRefereeRelationship: 'manager',
  voidRefereeCredit: 'manager',
  createPaymentProcessor: 'manager',
  markUserFeeCollected: 'manager',
  updateProcessorFeeStatus: 'manager',
  setCustomerCreditLimit: 'manager',
  revertCustomerCreditToEngine: 'manager',
  snoozeCustomerCreditReminder: 'manager',
  setCustomerEngineMax: 'manager',
  setCustomerStance: 'manager',
  disableCreditEngineForCustomer: 'owner',
  enableCreditEngineForCustomer: 'owner',
  createCreditEngineStance: 'owner',
  updateCreditEngineStance: 'owner',
  deleteCreditEngineStance: 'owner',
  setCreditEngineConfig: 'owner',
  bulkRevertCustomersToEngine: 'owner',
  setLineLandedCost: 'operator',
  setCustomerPricingRule: 'manager',
  setDefaultPricingRule: 'manager',
  updateSystemSetting: 'manager',
  mintPhotoUploadToken: 'manager',
  revokePhotoUploadToken: 'manager',
  createCustomerSheetSnapshot: 'operator',
  setLineBelowFloorReason: 'operator',
  resolveVendorApproval: 'manager',
  releaseLineForPicking: 'operator',
  releaseLinesForPicking: 'operator',
  recallLineFromPicking: 'operator',
  acknowledgeWarehouseAlert: 'operator',
  returnPickedUnits: 'operator',
  cancelFulfillmentLine: 'operator',
  // CAP-033 / TER-1564
  createContact: 'operator',
  updateContact: 'operator',
  archiveContact: 'manager',
  addContactRole: 'manager',
  linkContactToExistingEntity: 'manager',
  linkContactToUser: 'owner',
  createAppointment: 'operator',
  updateAppointment: 'operator',
  cancelAppointment: 'operator',
  completeAppointment: 'operator',
  updateVendor: 'operator',
  updateProcessor: 'owner',
  createItem: 'operator',
  updateItem: 'operator',
  toggleItemStatus: 'manager',
  resolveInvoiceDispute: 'manager',
  rejectInvoiceDispute: 'manager',
  // D2 — merge candidate review (manager-gated so viewers/operators cannot approve/dismiss)
  approveMergeCandidate: 'manager',
  dismissMergeCandidate: 'manager'
};

export const reversalPolicies: Record<CommandName, ReversalPolicy> = {
  createBatch: { disposition: 'terminal', guidance: 'Draft batches are deleted or edited directly before posting.' },
  updateBatch: { disposition: 'terminal', guidance: 'Use another update command with the intended field values.' },
  deleteBatch: { disposition: 'terminal', guidance: 'Deleted drafts are not reconstructed by command reversal.' },
  postPurchaseReceipt: { disposition: 'reversible', guidance: 'Marks posted intake, receipt, and generated vendor bills as reversed.' },
  createPurchaseOrder: { disposition: 'terminal', guidance: 'Cancel or edit the draft purchase order instead.' },
  updatePurchaseOrder: { disposition: 'terminal', guidance: 'Use another purchase order update with the intended field values.' },
  addPurchaseOrderLine: { disposition: 'terminal', guidance: 'Remove the unreceived purchase order line instead.' },
  updatePurchaseOrderLine: { disposition: 'terminal', guidance: 'Use another line update with the intended field values.' },
  removePurchaseOrderLine: { disposition: 'terminal', guidance: 'Removed unreceived lines are not reconstructed by command reversal.' },
  finalizePurchaseOrder: { disposition: 'reversible', guidance: 'Returns the purchase order to draft state when it has not been approved.' },
  unfinalizePurchaseOrder: { disposition: 'reversible', guidance: 'Returns the finalized purchase order to draft state for editing.' },
  approvePurchaseOrder: { disposition: 'reversible', guidance: 'Returns the purchase order to finalized state when no receipt depends on it.' },
  // UX-H04 / BE-009 (Execution Decision 5): partial receives are reversed the
  // same way — only THIS command's unposted drafts are undone; previously
  // posted receive progress on the lines is restored, not zeroed.
  receivePurchaseOrder: { disposition: 'reversible', guidance: 'Reverses unposted draft intake rows and restores the purchase order and its lines to their prior receiving state.' },
  cancelPurchaseOrder: { disposition: 'terminal', guidance: 'Cancelled purchase orders require a new order or explicit correction.' },
  recordVendorPrepayment: { disposition: 'reversible', guidance: 'Reverses the vendor payment record and restores prepayment availability.' },
  rejectBatch: { disposition: 'terminal', guidance: 'Rejected intake lots stay terminal; create a new intake row or correction if needed.' },
  flagBatch: { disposition: 'terminal', guidance: 'Flags add to the validation issues queue; resolve by editing the batch fields.' },
  verifyAllIntake: { disposition: 'reversible', guidance: 'Reverses generated receipts and vendor bills like postPurchaseReceipt.' },
  adjustBatchQuantity: { disposition: 'offsettable', guidance: 'Post an equal opposite quantity adjustment with a reason.' },
  setInventoryStatus: { disposition: 'reversible', guidance: 'Restores the prior batch status from the command snapshot.' },
  transferInventoryLocation: { disposition: 'reversible', guidance: 'Restores the prior batch location from the command snapshot.' },
  transferInventoryOwnership: { disposition: 'reversible', guidance: 'Restores the prior batch ownership/vendor fields from the command snapshot.' },
  setBatchPrice: { disposition: 'terminal', guidance: 'Use another price update or reprice the order before confirmation.' },
  setBatchLotInfo: { disposition: 'terminal', guidance: 'Use another lot-info update with the intended field values.' },
  attachBatchPhoto: { disposition: 'terminal', guidance: 'Replace or clear media through an explicit media correction.' },
  uploadBatchMedia: { disposition: 'terminal', guidance: 'Delete the media row via deleteBatchMedia if uploaded by mistake.' },
  setBatchMediaRole: { disposition: 'terminal', guidance: 'Run setBatchMediaRole again with the intended role value.' },
  publishBatchMedia: { disposition: 'terminal', guidance: 'Replace or delete the published media row; publish is not reversed via the bus.' },
  deleteBatchMedia: { disposition: 'terminal', guidance: 'Re-upload the media via uploadBatchMedia if the deletion was accidental.' },
  importBatchesCsv: { disposition: 'terminal', guidance: 'Imported drafts should be deleted or corrected row by row before posting.' },
  applyTags: { disposition: 'terminal', guidance: 'Apply tags again with the intended add/remove/replace mode.' },
  createSalesOrder: { disposition: 'terminal', guidance: 'Cancel or edit the draft order instead.' },
  addSalesOrderLine: { disposition: 'terminal', guidance: 'Remove the order line before posting.' },
  updateSalesOrderLine: { disposition: 'terminal', guidance: 'Use another line update with the intended field values.' },
  removeSalesOrderLine: { disposition: 'terminal', guidance: 'Removed draft lines are not reconstructed by command reversal.' },
  reserveInventoryForOrder: { disposition: 'offsettable', guidance: 'Cancel the sales order or manually release reservations through order correction.' },
  priceSalesOrder: { disposition: 'offsettable', guidance: 'Run repriceOrder or update line pricing with the intended strategy.' },
  confirmSalesOrder: { disposition: 'offsettable', guidance: 'Cancel or reprice the confirmed order before posting.' },
  cancelSalesOrder: { disposition: 'terminal', guidance: 'Cancelled orders require a new order or correction journal.' },
  postSalesOrder: { disposition: 'reversible', guidance: 'Restores inventory, reverses generated invoice impact, and marks the order reversed.' },
  allocateOrderToFulfillment: { disposition: 'terminal', guidance: 'Use fulfillment line/order controls before fulfillment is completed.' },
  applyClientCredit: { disposition: 'offsettable', guidance: 'Post an offsetting client ledger correction.' },
  setDeliveryWindow: { disposition: 'terminal', guidance: 'Set a new delivery window.' },
  logPayment: { disposition: 'reversible', guidance: 'Reverses unapplied payment logs and buyer-credit balance impact.' },
  allocatePayment: { disposition: 'reversible', guidance: 'Deletes payment allocations and restores invoice/payment/customer balances.' },
  unallocatePayment: { disposition: 'terminal', guidance: 'Re-allocate the payment if this was accidental.' },
  refundPayment: { disposition: 'terminal', guidance: 'Refunds are terminal money movement records; use a correction entry for mistakes.' },
  applyDiscount: { disposition: 'offsettable', guidance: 'Use a correction journal or invoice adjustment to offset the discount.' },
  postTransactionLedgerRow: { disposition: 'offsettable', guidance: 'Use source-specific reversal, void, or correction depending on the row trace.' },
  upsertTransactionType: { disposition: 'terminal', guidance: 'Edit the transaction type again or deactivate it.' },
  createVendorBill: { disposition: 'reversible', guidance: 'Marks generated vendor bill rows reversed.' },
  approveVendorBill: { disposition: 'offsettable', guidance: 'Update or void the vendor bill status through payable controls.' },
  scheduleVendorPayment: { disposition: 'offsettable', guidance: 'Reschedule the vendor bill or void the scheduled event.' },
  recordVendorPayment: { disposition: 'reversible', guidance: 'Voids the vendor payment and restores payable amount paid.' },
  voidVendorPayment: { disposition: 'terminal', guidance: 'Record a new vendor payment if the void was accidental.' },
  createPickList: { disposition: 'terminal', guidance: 'Adjust fulfillment allocation before packing or create a correction.' },
  recordWeighAndPack: { disposition: 'offsettable', guidance: 'Adjust the fulfillment line with corrected quantity/weight.' },
  markOrderFulfilled: { disposition: 'reversible', guidance: 'Returns the pick/order to open/posted state when no later archive depends on it.' },
  printLabels: { disposition: 'offsettable', guidance: 'Reprint labels or regenerate the manifest.' },
  adjustFulfillmentLine: { disposition: 'offsettable', guidance: 'Apply another fulfillment line adjustment.' },
  approveConnectorRequest: { disposition: 'reversible', guidance: 'Returns the connector request to open review.' },
  rejectConnectorRequest: { disposition: 'terminal', guidance: 'Rejected connector requests stay terminal; create or approve a new request.' },
  routeConnectorRequest: { disposition: 'reversible', guidance: 'Internal reassignment only; operators approve or reject inbound requests.' },
  createCorrectionJournalEntry: { disposition: 'reversible', guidance: 'Marks correction journal rows reversed.' },
  reverseCommandById: { disposition: 'terminal', guidance: 'Reversal commands are terminal audit records.' },
  documentCommandFailure: { disposition: 'terminal', guidance: 'Annotates a failed command journal row with a terminal reason. Cannot be reversed.' },
  restoreFromBackupPoint: { disposition: 'terminal', guidance: 'Restore preview is read-only and has no mutation to reverse.' },
  repriceOrder: { disposition: 'offsettable', guidance: 'Run repriceOrder again with the intended strategy.' },
  postPeriodAdjustments: { disposition: 'reversible', guidance: 'Marks posted correction journal rows reversed.' },
  lockPeriod: { disposition: 'terminal', guidance: 'Period locks are terminal closeout controls.' },
  archivePeriod: { disposition: 'terminal', guidance: 'Archive runs are terminal; restore is offline/read-only in app.' },
  createVendor: { disposition: 'terminal', guidance: 'Edit the vendor profile or deactivate it if it was created by mistake.' },
  createCustomerNeed: { disposition: 'terminal', guidance: 'Close or edit the customer need if it was entered by mistake.' },
  updateCustomerNeed: { disposition: 'terminal', guidance: 'Use another update with the intended need values.' },
  createVendorSupply: { disposition: 'terminal', guidance: 'Close or edit the vendor stock row if it was entered by mistake.' },
  updateVendorSupply: { disposition: 'terminal', guidance: 'Use another update with the intended vendor stock values.' },
  acceptMatchmakingMatch: { disposition: 'offsettable', guidance: 'Dismiss the match or reopen the need/supply from the matchmaking grid.' },
  dismissMatchmakingMatch: { disposition: 'offsettable', guidance: 'Accept a new or reopened match if the dismissal was accidental.' },
  reopenMatchmakingMatch: { disposition: 'reversible', guidance: 'Call acceptMatchmakingMatch or dismissMatchmakingMatch to set status again.' },
  updateMatchmakingSettings: { disposition: 'offsettable', guidance: 'Run updateMatchmakingSettings again with the intended values.' },
  noteMatchmakingOutreach: { disposition: 'terminal', guidance: 'Outreach notes are informational audit records; the snooze expires automatically after 30 days.' },
  dismissMatchmakingWorkQueueItem: { disposition: 'terminal', guidance: 'Dismissals expire after 30 days. Re-queue by waiting for the snooze to lapse.' },
  setItemAlias: { disposition: 'reversible', guidance: 'Restores the prior alias value from the command snapshot.' },
  createReferee: { disposition: 'terminal', guidance: 'Edit or deactivate the referee profile if it was created by mistake.' },
  updateReferee: { disposition: 'terminal', guidance: 'Use another update with the intended referee values.' },
  addRefereeRelationship: { disposition: 'terminal', guidance: 'Deactivate the referee relationship if it was added by mistake.' },
  updateRefereeRelationship: { disposition: 'terminal', guidance: 'Use another update with the intended relationship values.' },
  deactivateRefereeRelationship: { disposition: 'terminal', guidance: 'Add a new relationship if the deactivation was accidental.' },
  voidRefereeCredit: { disposition: 'reversible', guidance: 'Restores the credit to accrued status and updates referee balance.' },
  createPaymentProcessor: { disposition: 'terminal', guidance: 'Edit or deactivate the payment processor if it was created by mistake.' },
  markUserFeeCollected: { disposition: 'reversible', guidance: 'Reverses the fee collection record and updates user fee status.' },
  updateProcessorFeeStatus: { disposition: 'terminal', guidance: 'Use another update with the intended fee status values.' },
  setCustomerCreditLimit: { disposition: 'reversible', guidance: 'Use revertCustomerCreditToEngine to clear the manual override.' },
  revertCustomerCreditToEngine: { disposition: 'reversible', guidance: 'Apply another manual credit limit with setCustomerCreditLimit if reversion was unintended.' },
  snoozeCustomerCreditReminder: { disposition: 'reversible', guidance: 'Reset the snooze with another snooze call or by reverting to engine.' },
  setCustomerEngineMax: { disposition: 'reversible', guidance: 'Call setCustomerEngineMax again with the prior cap or null to clear it.' },
  setCustomerStance: { disposition: 'reversible', guidance: 'Call setCustomerStance with the prior stance id (or null for default).' },
  disableCreditEngineForCustomer: { disposition: 'reversible', guidance: 'Use enableCreditEngineForCustomer to restore engine processing.' },
  enableCreditEngineForCustomer: { disposition: 'reversible', guidance: 'Use disableCreditEngineForCustomer with a reason if disable is needed again.' },
  createCreditEngineStance: { disposition: 'reversible', guidance: 'Delete the stance if it was created by mistake (only allowed when unused).' },
  updateCreditEngineStance: { disposition: 'reversible', guidance: 'Call updateCreditEngineStance again with the prior values from stance history.' },
  deleteCreditEngineStance: { disposition: 'terminal', guidance: 'Deleted stances cannot be reconstructed; recreate the stance with createCreditEngineStance if needed.' },
  setCreditEngineConfig: { disposition: 'reversible', guidance: 'Call setCreditEngineConfig again with the prior values from config history.' },
  bulkRevertCustomersToEngine: { disposition: 'terminal', guidance: 'Bulk rollout is terminal; per-customer manual overrides can be restored individually.' },
  setLineLandedCost: { disposition: 'reversible', guidance: 'Restores the prior landed COGS, basis, and resolution flag from the command snapshot.' },
  setCustomerPricingRule: { disposition: 'reversible', guidance: 'Restores the prior customer pricing rule from the command snapshot.' },
  setDefaultPricingRule: { disposition: 'reversible', guidance: 'Restores the prior default pricing rule from the command snapshot.' },
  updateSystemSetting: { disposition: 'offsettable', guidance: 'Run updateSystemSetting again with the prior value to restore the previous state.' },
  mintPhotoUploadToken: { disposition: 'reversible', guidance: 'Use revokePhotoUploadToken with the returned tokenId to invalidate the share link immediately.' },
  revokePhotoUploadToken: { disposition: 'terminal', guidance: 'Mint a new photo upload share link if the revoke was accidental — the previous raw token is unrecoverable.' },
  createCustomerSheetSnapshot: { disposition: 'terminal', guidance: 'Snapshots are append-only audit records of what was sent. Create a new sheet instead.' },
  setLineBelowFloorReason: { disposition: 'reversible', guidance: 'Re-run setLineBelowFloorReason with the updated reason and note.' },
  resolveVendorApproval: { disposition: 'reversible', guidance: 'Re-run resolveVendorApproval with the intended state to flip the sign-off.' },
  releaseLineForPicking: { disposition: 'reversible', guidance: 'Use recallLineFromPicking to reverse while the fulfillment line is still open.' },
  releaseLinesForPicking: { disposition: 'reversible', guidance: 'Use recallLineFromPicking per line to reverse while all fulfillment lines are still open.' },
  recallLineFromPicking: { disposition: 'terminal', guidance: 'Release the line again with releaseLineForPicking if the recall was unintended.' },
  acknowledgeWarehouseAlert: { disposition: 'terminal', guidance: 'Acknowledgement is a one-way audit mark. Review the bag and reconcile if needed.' },
  returnPickedUnits: { disposition: 'offsettable', guidance: 'Re-record the pick quantity via recordWeighAndPack if the return was accidental.' },
  cancelFulfillmentLine: { disposition: 'terminal', guidance: 'Contact sales to reopen the order line and re-release for picking if cancellation was incorrect.' },
  // CAP-033 / TER-1564
  createContact: { disposition: 'terminal', guidance: 'Use archiveContact to deactivate; new contacts cannot be unbuilt.' },
  updateContact: { disposition: 'offsettable', guidance: 'Run updateContact again with the prior values.' },
  archiveContact: { disposition: 'terminal', guidance: 'Cannot be reversed; create a new contact if archiving was a mistake.' },
  addContactRole: { disposition: 'terminal', guidance: 'Role additions are append-only; do not remove roles via reversal.' },
  linkContactToExistingEntity: { disposition: 'offsettable', guidance: 'Unlink by clearing the entity row contact_id via an admin path.' },
  linkContactToUser: { disposition: 'offsettable', guidance: 'Unlink by clearing users.contact_id via an admin path.' },
  createAppointment: { disposition: 'reversible', guidance: 'Use cancelAppointment to mark the appointment cancelled.' },
  updateAppointment: { disposition: 'offsettable', guidance: 'Run updateAppointment again with the prior values.' },
  cancelAppointment: { disposition: 'terminal', guidance: 'Cancelled appointments cannot be reactivated; create a new appointment instead.' },
  completeAppointment: { disposition: 'terminal', guidance: 'Completed appointments cannot be uncompleted.' },
  updateVendor: { disposition: 'offsettable', guidance: 'Run updateVendor again with the prior values.' },
  updateProcessor: { disposition: 'offsettable', guidance: 'Run updateProcessor again with the prior values.' },
  createItem: { disposition: 'terminal', guidance: 'Use toggleItemStatus to deactivate; items cannot be deleted if referenced by batches or orders.' },
  updateItem: { disposition: 'offsettable', guidance: 'Run updateItem again with the prior values.' },
  toggleItemStatus: { disposition: 'reversible', guidance: 'Run toggleItemStatus again to re-activate the item.' },
  resolveInvoiceDispute: { disposition: 'terminal', guidance: 'Resolved disputes are final. Use rejectInvoiceDispute to change to rejected instead.' },
  rejectInvoiceDispute: { disposition: 'terminal', guidance: 'Rejected disputes are final. Use resolveInvoiceDispute to change to resolved instead.' },
  // D2 — merge candidate review is a one-way audit mark; not reversible
  approveMergeCandidate: { disposition: 'terminal', guidance: 'Marking a candidate reviewed is a one-way audit mark. Dismiss the candidate instead if the match is not valid.' },
  dismissMergeCandidate: { disposition: 'terminal', guidance: 'Dismissal is a one-way audit mark. Re-run the deduplication scan to regenerate candidates if needed.' }
};

export const reversibleCommands = new Set<CommandName>(
  commandNames.filter((name) => reversalPolicies[name].disposition === 'reversible')
);

export function commandLabelFor(name: unknown) {
  if (typeof name !== 'string') return '';
  if (commandNames.includes(name as CommandName)) return commandLabels[name as CommandName];
  return name
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replace(/[_-]+/g, ' ')
    .trim()
    .replace(/^./, (letter) => letter.toUpperCase());
}
